

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  user-management-service:
    build: ./microservices/user-management-service/backend
    container_name: user-management-service
    ports:
      - '5000:5000'

    env_file:
    - ./microservices/user-management-service/backend/.env
  
    environment:
      - MONGO_URI=mongodb+srv://dbUser:GfQkn6g5yX0XYDBJ@ds-assignment-teamdb.ybkozh7.mongodb.net/users?retryWrites=true&w=majority&appName=DS-Assignment-TeamDB
      - JWT_SECRET=DS_secret_jwt_key
      
    depends_on:
    - mongo
    

  restaurant-management-service:
    build: ./microservices/restaurant-management-service/backend
    container_name: restaurant-management-service
    ports:
      - '5400:5400'

    env_file:
    - ./microservices/restaurant-management-service/backend/.env

    environment:
      - MONGODB_URI=mongodb+srv://dbUser:GfQkn6g5yX0XYDBJ@ds-assignment-teamdb.ybkozh7.mongodb.net/restaurant-db?retryWrites=true&w=majority&appName=DS-Assignment-TeamDB
      - JWT_SECRET=DS_secret_jwt_key

    depends_on:
    - mongo

  delivery-service:
    build: ./microservices/delivery-service/backend
    container_name: delivery-service
    ports:
      - '5600:5600'

    env_file:
    - ./microservices/delivery-service/.env

    environment:
      - MONGO_URI=MONGO_URI=mongodb+srv://dbUser:GfQkn6g5yX0XYDBJ@ds-assignment-teamdb.ybkozh7.mongodb.net/delivery_service?retryWrites=true&w=majority&appName=DS-Assignment-TeamDB
      - JWT_SECRET=DS_secret_jwt_key
    
    depends_on:
    - mongo
    

  order-service:
    build: MONGO_URI=mongodb+srv://dbUser:GfQkn6g5yX0XYDBJ@ds-assignment-teamdb.ybkozh7.mongodb.net/order_service_db?retryWrites=true&w=majority&appName=DS-Assignment-TeamDB
    container_name: order-service
    ports:
      - '5500:5500'

    env_file:
    - ./microservices/order-management-service/.env

    environment:
      - MONGO_URI=mongodb+srv://dbUser:GfQkn6g5yX0XYDBJ@ds-assignment-teamdb.ybkozh7.mongodb.net/order_service_db?retryWrites=true&w=majority&appName=DS-Assignment-TeamDB
      - JWT_SECRET=DS_secret_jwt_key

    depends_on:
    - mongo

  notification-service:
    build: ./microservices/notification-service/backend
    container_name: notification-service
    ports:
      - '5200:5200'

    env_file:
    - ./microservices/notification-service/backend/.env
    environment:
      - MONGO_URI=mongodb+srv://dbUser:GfQkn6g5yX0XYDBJ@ds-assignment-teamdb.ybkozh7.mongodb.net/notifications?retryWrites=true&w=majority&appName=DS-Assignment-TeamDB
      
    depends_on:
      - mongo

  payment-service:
    build: ./microservices/payment-service/project-PaymentService/backend
    container_name: payment-service
    ports:
      - '5300:5300'
    env_file: 
    - ./microservices/payment-service/project-PaymentService/backend/.env
    environment:
      - MONGO_URI=mongodb+srv://dbUser:GfQkn6g5yX0XYDBJ@ds-assignment-teamdb.ybkozh7.mongodb.net/payments?retryWrites=true&w=majority&appName=DS-Assignment-TeamDB
      
    depends_on:
      - mongo

volumes:
  mongo_data:
