apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-deployment
  labels:
    app: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - name: user-management-container
        image: user-management-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: JWT_SECRET
          value: "your_jwt_secret"
        - name: MONGO_URI
          value: "mongodb://your-mongo-url"

---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  type: NodePort
  selector:
    app: user-management
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
